CXX		=	g++
CXXFLAGS	= 	-Wall -Werror -std=c++0x
INCLUDE		=	-I/usr/local/include
LDFLAGS		=	-L/usr/local/lib -lcurl

BINARY		=	download

all:
	$(CXX) -o $(BINARY) $(INCLUDE) $(LDFLAGS) $(CXXFLAGS) *.cpp
